service:
  name: anagrams

log:
  debug: true

locale:
  language: fr
  normalize_unicode: true

dictionary:
  files: [./data/french.txt, ./data/english.txt]

lru_cache:
  capacity: 10

server:
  port: :8082

client:
  concurrent_requests: 10
  test_words:
  - dear
  - read
  - test
  - écart
  - hello
  - raécs 
  - otrpe